# Generated by Django 6.0.6 on 2026-06-10 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antecedente',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bênção',
                'verbose_name_plural': 'Bênçãos',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condição',
                'verbose_name_plural': 'Condições',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descritor',
                'verbose_name_plural': 'Descritores',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('custo_enfase', models.IntegerField(default=0)),
                ('execucao', models.CharField(blank=True, default='ação', max_length=24)),
                ('fonte_tipo', models.CharField(choices=[('legado', 'Legado'), ('maldicao', 'Maldição'), ('classe', 'Classe'), ('trilha', 'Trilha'), ('antecedente', 'Antecedente'), ('bencao', 'Bênção'), ('outro', 'Outro')], default='outro', max_length=14)),
                ('fonte_nome', models.CharField(blank=True, default='', max_length=80)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('escudo', 'Escudo'), ('equipamento', 'Equipamento'), ('municao', 'Munição'), ('consumivel', 'Consumível'), ('magitech', 'Engenhoca Magitech'), ('servico', 'Serviço'), ('transporte', 'Transporte'), ('outro', 'Outro')], default='equipamento', max_length=20)),
                ('categoria', models.CharField(blank=True, default='', help_text='simples/marcial/fogo/regional para armas; leve/pesada para armaduras', max_length=20)),
                ('empunhadura', models.CharField(blank=True, choices=[('uma_mao', 'Uma mão'), ('duas_maos', 'Duas mãos'), ('', '—')], default='', max_length=12)),
                ('preco', models.IntegerField(blank=True, help_text='Preço em Trocados (T$)', null=True)),
                ('volume', models.IntegerField(default=0)),
                ('dano', models.CharField(blank=True, default='', max_length=20)),
                ('alcance', models.CharField(blank=True, default='', max_length=20)),
                ('reducao_dano', models.IntegerField(default=0)),
                ('descritores_texto', models.CharField(blank=True, default='', help_text='Descritores com parâmetros, ex: RECARREGÁVEL (1A)', max_length=255)),
                ('nome_registrado', models.CharField(blank=True, default='', help_text='Nome de patente (engenhocas magitech)', max_length=160)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('descritores', models.ManyToManyField(blank=True, related_name='itens', to='core.descritor')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Legado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legado',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('camada', models.CharField(choices=[('truque', 'Truque'), ('superficial', 'Camada Superficial'), ('rasa', 'Camada Rasa'), ('profunda', 'Camada Profunda')], default='truque', max_length=12)),
                ('tipo', models.CharField(choices=[('controle', 'Controle'), ('ofensivo', 'Ofensivo'), ('utilitario', 'Utilitário')], default='utilitario', max_length=12)),
                ('custo_enfase', models.IntegerField(default=0)),
                ('execucao', models.CharField(blank=True, default='ação', max_length=24)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magia',
                'ordering': ['camada', 'nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maldicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maldição',
                'verbose_name_plural': 'Maldições',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('efeito_resumo', models.CharField(blank=True, default='', max_length=120)),
                ('aumento_preco', models.IntegerField(default=300)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Especial',
                'verbose_name_plural': 'Materiais Especiais',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('atributo_padrao', models.CharField(choices=[('FOR', 'Força'), ('DES', 'Destreza'), ('CON', 'Constituição'), ('INT', 'Inteligência'), ('SAB', 'Sabedoria'), ('CAR', 'Carisma')], default='INT', max_length=3)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perícia',
                'verbose_name_plural': 'Perícias',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pronomes', models.CharField(blank=True, default='', max_length=40)),
                ('jogadore', models.CharField(blank=True, default='', max_length=80)),
                ('nivel', models.IntegerField(default=1)),
                ('heranca', models.CharField(blank=True, default='', max_length=80)),
                ('melancolia', models.CharField(blank=True, default='', max_length=200)),
                ('f_for', models.IntegerField(default=0, verbose_name='FOR')),
                ('f_des', models.IntegerField(default=0, verbose_name='DES')),
                ('f_con', models.IntegerField(default=0, verbose_name='CON')),
                ('f_int', models.IntegerField(default=0, verbose_name='INT')),
                ('f_sab', models.IntegerField(default=0, verbose_name='SAB')),
                ('f_car', models.IntegerField(default=0, verbose_name='CAR')),
                ('pv_maximo', models.IntegerField(default=10)),
                ('pv_atual', models.IntegerField(default=10)),
                ('pv_temporario', models.IntegerField(default=0)),
                ('dados_vida_total', models.IntegerField(default=1)),
                ('dados_vida_usados', models.IntegerField(default=0)),
                ('morte_sucessos', models.IntegerField(default=0)),
                ('morte_falhas', models.IntegerField(default=0)),
                ('catarse', models.IntegerField(default=0)),
                ('enfase_total', models.IntegerField(default=2)),
                ('enfase_atual', models.IntegerField(default=2)),
                ('sombra', models.IntegerField(default=0)),
                ('reducao_dano', models.IntegerField(default=0)),
                ('iniciativa_bonus', models.IntegerField(default=0)),
                ('tamanho', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Médie', 'Médie'), ('Grande', 'Grande')], default='Médio', max_length=12)),
                ('deslocamento', models.CharField(default='9 m / 6 q', max_length=20)),
                ('trocados', models.IntegerField(default=0)),
                ('pecas', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('antecedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.antecedente')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classe')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='personagens', to='core.habilidade')),
                ('legado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.legado')),
                ('magias', models.ManyToManyField(blank=True, related_name='personagens', to='core.magia')),
                ('maldicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maldicao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sigilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('prefixo', 'Prefixo'), ('sufixo', 'Sufixo')], default='prefixo', max_length=8)),
                ('grau', models.IntegerField(default=1)),
                ('equipamento', models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('escudo', 'Escudo'), ('vestimenta', 'Vestimenta')], default='arma', max_length=12)),
                ('disparo', models.CharField(blank=True, default='', max_length=12)),
                ('cargas', models.IntegerField(default=2)),
                ('efeito', models.TextField(blank=True)),
                ('imbuindo', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sigilo',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('equipado', models.BooleanField(default=False)),
                ('fragmentos', models.IntegerField(default=0, help_text='Fragmentos arcanos ocupados pelo item')),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='core.item')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.materialespecial')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.personagem')),
                ('sigilo_prefixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sigilo')),
                ('sigilo_sufixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sigilo')),
            ],
            options={
                'verbose_name': 'Entrada de Inventário',
                'verbose_name_plural': 'Entradas de Inventário',
            },
        ),
        migrations.CreateModel(
            name='Sinapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('rara', 'Rara'), ('muito_rara', 'Muito Rara')], default='comum', max_length=12)),
                ('multiplicador', models.IntegerField(default=1)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinapse',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trilha',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personagem',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trilha'),
        ),
        migrations.CreateModel(
            name='PericiaPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(choices=[('FOR', 'Força'), ('DES', 'Destreza'), ('CON', 'Constituição'), ('INT', 'Inteligência'), ('SAB', 'Sabedoria'), ('CAR', 'Carisma')], default='INT', max_length=3)),
                ('proficiente', models.BooleanField(default=False)),
                ('expert', models.BooleanField(default=False)),
                ('pericia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.pericia')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='core.personagem')),
            ],
            options={
                'verbose_name': 'Perícia do Personagem',
                'verbose_name_plural': 'Perícias do Personagem',
                'unique_together': {('personagem', 'pericia')},
            },
        ),
    ]
