# Generated by Django 6.0.6 on 2026-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='dados_vida_total',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='morte_sucessos',
        ),
        migrations.AddField(
            model_name='personagem',
            name='inspiracao',
            field=models.BooleanField(default=False, verbose_name='Inspiração'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='p_car',
            field=models.BooleanField(default=False, verbose_name='Proficiência CAR'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='p_con',
            field=models.BooleanField(default=False, verbose_name='Proficiência CON'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='p_des',
            field=models.BooleanField(default=False, verbose_name='Proficiência DES'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='p_for',
            field=models.BooleanField(default=False, verbose_name='Proficiência FOR'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='p_int',
            field=models.BooleanField(default=False, verbose_name='Proficiência INT'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='p_sab',
            field=models.BooleanField(default=False, verbose_name='Proficiência SAB'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='f_car',
            field=models.IntegerField(default=10, verbose_name='CAR'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='f_con',
            field=models.IntegerField(default=10, verbose_name='CON'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='f_des',
            field=models.IntegerField(default=10, verbose_name='DES'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='f_for',
            field=models.IntegerField(default=10, verbose_name='FOR'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='f_int',
            field=models.IntegerField(default=10, verbose_name='INT'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='f_sab',
            field=models.IntegerField(default=10, verbose_name='SAB'),
        ),
    ]
