# Generated by Django 6.0.6 on 2026-06-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_personagem_dados_vida_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='pecas',
        ),
    ]
