# Generated by Django 6.0.6 on 2026-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_personagem_pecas'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='agua',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='personagem',
            name='condicoes_ativas',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personagem',
            name='desafio_falhas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='desafio_sucessos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='notas_terreno',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='personagem',
            name='racoes',
            field=models.IntegerField(default=5),
        ),
    ]
