# Generated by Django 6.0.6 on 2026-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personagem_agua_personagem_condicoes_ativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioentrada',
            name='atributo_ataque',
            field=models.CharField(choices=[('FOR', 'Força'), ('DES', 'Destreza'), ('CON', 'Constituição'), ('INT', 'Inteligência'), ('SAB', 'Sabedoria'), ('CAR', 'Carisma')], default='FOR', max_length=3),
        ),
        migrations.AddField(
            model_name='inventarioentrada',
            name='proficiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personagem',
            name='iniciativa_atual',
            field=models.IntegerField(default=0),
        ),
    ]
