# Generated by Django 6.0.6 on 2026-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventarioentrada_atributo_ataque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='agua',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='desafio_falhas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='desafio_sucessos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='iniciativa_atual',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='racoes',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
