# Generated by Django 6.0.6 on 2026-06-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_personagem_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='diario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
