# Generated by Django 6.0.6 on 2026-06-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_personagem_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='inspiracao',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inspiração'),
        ),
    ]
