# Generated by Django 6.0.6 on 2026-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_personagem_inspiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='p_car',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Proficiência CAR'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='p_con',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Proficiência CON'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='p_des',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Proficiência DES'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='p_for',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Proficiência FOR'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='p_int',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Proficiência INT'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='p_sab',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Proficiência SAB'),
        ),
    ]
