# Generated by Django 6.0.6 on 2026-06-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_personagem_p_car_alter_personagem_p_con_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='logs',
            field=models.TextField(blank=True, default='', verbose_name='Logs'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='diario',
            field=models.TextField(blank=True, default='', verbose_name='Diário'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='notas_terreno',
            field=models.TextField(blank=True, default='', verbose_name='Notas de Terreno'),
        ),
    ]
