# Generated by Django 6.0.6 on 2026-06-27 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_personagem_logs_alter_personagem_diario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.personagem')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
