# Generated by Django 6.0.6 on 2026-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_registrolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='oculto',
            field=models.BooleanField(default=False, verbose_name='Oculto'),
        ),
    ]
