# Generated by Django 6.0.6 on 2026-07-12 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_personagem_oculto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_mestrando', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='personagem',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens', to='core.mesa'),
        ),
    ]
