# Generated by Django 6.0.6 on 2026-07-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mesa_personagem_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenaMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('combate', 'Combate'), ('desafio', 'Desafio de Perícias'), ('social', 'Interação / Social'), ('descanso', 'Descanso / Acampamento')], default='combate', max_length=20)),
                ('turno_atual', models.IntegerField(default=0)),
                ('anotacoes', models.TextField(blank=True, default='', help_text='Detalhes globais, clima, pistas')),
                ('desafio_sucessos', models.IntegerField(default=0)),
                ('desafio_falhas', models.IntegerField(default=0)),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cena_atual', to='core.mesa')),
            ],
            options={
                'verbose_name': 'Cena da Mesa',
            },
        ),
        migrations.CreateModel(
            name='CenaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('iniciativa', models.IntegerField(default=0)),
                ('pv_atual', models.IntegerField(blank=True, null=True)),
                ('pv_maximo', models.IntegerField(blank=True, null=True)),
                ('cena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.cenamesa')),
                ('personagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personagem')),
            ],
            options={
                'ordering': ['-iniciativa', 'id'],
            },
        ),
    ]
